### Exercise
# Loop over DataFrame (2)

The row data that's generated by `iterrows()` on every run is a Pandas Series. This format is not very convenient to print out. Luckily, you can easily select variables from the Pandas Series using square brackets:

In [ ]:
for lab, row in brics.iterrows():
    print(row['country'])

## Instructions
* Using the iterators `lab` and `row`, adapt the code in the for loop such that the first iteration print outs "US: 809", the second iteration "AUS: 731", and so on.
* The output should be in the form "country: cars_per_cap". Make sure to print out this exact string (with correct spacing).
  * *You can use `str()` to convert your integer data to a string so that you can print it in conjunction with the country label*.

import cars data

In [3]:
import pandas as pd
cars = pd.read_csv('cars.csv', index_col=0)

Adapt for loop

In [5]:
for lab, row in cars.iterrows():
    print(f"{lab}: {row['cars_per_cap']}")

US: 809
AUS: 731
JAP: 588
IN: 18
RU: 200
MOR: 70
EG: 45

In [9]:
many_cars =  cpc > 500
many_cars

US      True
AUS     True
JAP     True
IN     False
RU     False
MOR    False
EG     False
Name: cars_per_cap, dtype: bool

In [10]:
car_maniac = cars[many_cars]
car_maniac

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False

In [11]:
print(cars[cars['cars_per_cap'] > 500])

     cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False